In [1]:
import numpy as np
np.__version__

'1.18.2'

In [0]:
print(dir(np))

In [4]:
x = np.array([1,3])
x

array([1, 3])

In [5]:
print(x)
type(x)

[1 3]


numpy.ndarray

In [6]:
np.array([1.3, 2.4, 4.5])

array([1.3, 2.4, 4.5])

### Tablica 2D

In [0]:
z = np.array([[1,2],[-3,1]]) #tworząc tablicę dwuwymiarową wypisujemy listy zagnieżdżone

In [10]:
z.ndim  #wymiar tablicy

2

In [11]:
z.shape #kształt tablicy

(2, 2)

In [16]:
y = np.array([[1,2,4],[5,4,1]])   #tablica dwuwymiarowa  - 3 wiersze, 3 kolumny
print(y)
y.shape   #zwrócony wynik oznacza, że tablica jest dwuwymiarowa i posiada 3 elementy

[[1 2 4]
 [5 4 1]]


(2, 3)

### Tablica 3D

In [19]:
x = np.array(
    [[[4,3,1],
      [3,1,2]],
     
     [[4,1,1],
      [4,2,1]]]
)
print(x)

[[[4 3 1]
  [3 1 2]]

 [[4 1 1]
  [4 2 1]]]


In [20]:
x.ndim

3

In [21]:
x.shape  #zwrócony wynik oznacza, że mamy dwie tablice, dwa wiersze, trzy kolumny

(2, 2, 3)